[package]
name = "parliament-desktop"
version = "0.1.0"
description = "Parliament Desktop"
authors = []
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "parliament_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "parliament-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
